'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property Signature() As String
        Get
            Return CType(Me("Signature"),String)
        End Get
        Set
            Me("Signature") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property BodyPrice() As String
        Get
            Return CType(Me("BodyPrice"),String)
        End Get
        Set
            Me("BodyPrice") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property BodyRef() As String
        Get
            Return CType(Me("BodyRef"),String)
        End Get
        Set
            Me("BodyRef") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property BodyText() As String
        Get
            Return CType(Me("BodyText"),String)
        End Get
        Set
            Me("BodyText") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property strTitleForm1() As String
        Get
            Return CType(Me("strTitleForm1"),String)
        End Get
        Set
            Me("strTitleForm1") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property BodyCreditControl() As String
        Get
            Return CType(Me("BodyCreditControl"),String)
        End Get
        Set
            Me("BodyCreditControl") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property Account1SPW() As String
        Get
            Return CType(Me("Account1SPW"),String)
        End Get
        Set
            Me("Account1SPW") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property Account2SPW() As String
        Get
            Return CType(Me("Account2SPW"),String)
        End Get
        Set
            Me("Account2SPW") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property Account3SPW() As String
        Get
            Return CType(Me("Account3SPW"),String)
        End Get
        Set
            Me("Account3SPW") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property Account4SPW() As String
        Get
            Return CType(Me("Account4SPW"),String)
        End Get
        Set
            Me("Account4SPW") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property Account5SPW() As String
        Get
            Return CType(Me("Account5SPW"),String)
        End Get
        Set
            Me("Account5SPW") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property Account1SPO() As String
        Get
            Return CType(Me("Account1SPO"),String)
        End Get
        Set
            Me("Account1SPO") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property Account2SPO() As String
        Get
            Return CType(Me("Account2SPO"),String)
        End Get
        Set
            Me("Account2SPO") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property Account3SPO() As String
        Get
            Return CType(Me("Account3SPO"),String)
        End Get
        Set
            Me("Account3SPO") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property Account4SPO() As String
        Get
            Return CType(Me("Account4SPO"),String)
        End Get
        Set
            Me("Account4SPO") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property Account5SPO() As String
        Get
            Return CType(Me("Account5SPO"),String)
        End Get
        Set
            Me("Account5SPO") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property TBadress1() As String
        Get
            Return CType(Me("TBadress1"),String)
        End Get
        Set
            Me("TBadress1") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property TBadress2() As String
        Get
            Return CType(Me("TBadress2"),String)
        End Get
        Set
            Me("TBadress2") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property TBadress3() As String
        Get
            Return CType(Me("TBadress3"),String)
        End Get
        Set
            Me("TBadress3") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property TBadress4() As String
        Get
            Return CType(Me("TBadress4"),String)
        End Get
        Set
            Me("TBadress4") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("tempvalue")>  _
    Public Property TBadress5() As String
        Get
            Return CType(Me("TBadress5"),String)
        End Get
        Set
            Me("TBadress5") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property CBautoSearch() As Boolean
        Get
            Return CType(Me("CBautoSearch"),Boolean)
        End Get
        Set
            Me("CBautoSearch") = value
        End Set
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=|DataDirectory|\Clients.accdb")>  _
    Public ReadOnly Property ClientsConnectionString() As String
        Get
            Return CType(Me("ClientsConnectionString"),String)
        End Get
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.OrderNumber.MySettings
            Get
                Return Global.OrderNumber.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
